name: PHP

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  syntax:
    name: "Check Syntax (${{ matrix.php }})"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v4
      - run: echo "::add-matcher::.github/php-syntax.json"
      - run: |
          ! find . -type f -name '*.php' -exec php -l '{}' \; 2>&1 |grep -v '^No syntax errors detected'
